/*

An event is a signal that is generated by a certain dome node. We can listen for these events. The event happens no matter if we listen or not.

Types of events:

*/
const h1 = document.querySelector('h1');

const alertH1 = function (e) {
  alert('addEventListener: Great! You are reading the heading');
};
h1.addEventListener('mouseenter', alertH1);

// removing an event in case we don't need it or whenever you only want to listen to the event only once or in a setTimeout function as callback

setTimeout(() => h1.removeEventListener('mouseenter', alertH1), 3000);

// a different approach to adding an event on mouse hover

// h1.onmouseenter = function (e) {
//   alert('onmouseenter: Great! You are reading the heading');
// };

// using an HTML attribute (should not be used...):
{
  /* <h1 onclick="alert('HTML alert')"> */
}
